name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Or your main branch name (e.g., main, master)

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Use a Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use the checkout action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Refers to repository Secrets
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Build from the current directory
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/test-app:working
            ${{ secrets.DOCKERHUB_USERNAME }}/test-app:200
            ${{ secrets.DOCKERHUB_USERNAME }}/test-app:${{ github.sha }} 
